# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170828_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='수업의 이름')),
                ('code', models.TextField(default='cbb72bed')),
                ('year', models.IntegerField(default=2017, help_text='수업이 진행된 학년')),
                ('semester', models.IntegerField(default=1, help_text='수업이 진행된 학기')),
            ],
        ),
    ]
