# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtime',
            options={'verbose_name': '강의 분반', 'verbose_name_plural': '강의 분반들'},
        ),
        migrations.AddField(
            model_name='classtime',
            name='class_no',
            field=models.TextField(default=1, help_text='분반'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='code',
            field=models.TextField(default='23e363a3'),
        ),
    ]
