# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170829_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='class_no',
            field=models.IntegerField(default=1, verbose_name='분반'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='code',
            field=models.TextField(default='05f1e05c', help_text='절대 수정하지 마세요!!', verbose_name='수업 이름 (수정금지)'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='name',
            field=models.CharField(max_length=200, verbose_name='수업 이름'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='semester',
            field=models.IntegerField(default=1, verbose_name='수업 학기'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='year',
            field=models.IntegerField(default=2018, verbose_name='수업 연도'),
        ),
    ]
