# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170829_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='code',
            field=models.CharField(default='798ef0e0', help_text='절대 수정하지 마세요!!', max_length=10, verbose_name='수업 이름 (수정금지)'),
        ),
    ]
