# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170829_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtime',
            name='code',
        ),
    ]
