# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('class_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_footsteps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
