# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '과제물', 'verbose_name_plural': '과제물'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='hw_file',
            field=models.FileField(null=True, upload_to='', verbose_name='과제물 파일'),
        ),
    ]
