# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20170830_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='parent_class',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
