# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_remove_classtime_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0003_auto_20170830_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 시간')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('hw_file', models.FileField(null=True, upload_to='', verbose_name='과제물 파일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClassTime', verbose_name='소속 수업')),
            ],
            options={
                'verbose_name': '과제물',
                'verbose_name_plural': '과제물',
            },
        ),
    ]
